# Generated by Django 4.2.4 on 2023-09-07 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HWapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='product',
            new_name='products',
        ),
    ]
